// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASpO_sELhoD9HL6Gt2vonq7ng9SBXSdgk',
    appId: '1:1066577466848:web:48bfaa57cb8b5c12a04785',
    messagingSenderId: '1066577466848',
    projectId: 'barbershopalexisburgos',
    authDomain: 'barbershopalexisburgos.firebaseapp.com',
    storageBucket: 'barbershopalexisburgos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBKIgOFMgt5IShbG_QHESTMaCd_5w1QJ8',
    appId: '1:1066577466848:android:351644156e016bbea04785',
    messagingSenderId: '1066577466848',
    projectId: 'barbershopalexisburgos',
    storageBucket: 'barbershopalexisburgos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVcvK4s2buG2NtzptCGBynGpGodQbNOm8',
    appId: '1:1066577466848:ios:22ea6fb94ec9dcc2a04785',
    messagingSenderId: '1066577466848',
    projectId: 'barbershopalexisburgos',
    storageBucket: 'barbershopalexisburgos.appspot.com',
    iosClientId: '1066577466848-qeol3klg2l328ooqroo3fvnf1lggfb01.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberShopAlexis',
  );
}
